### ISSUE TITLE
iTunes HTTP URL is not giving exact app version

### ISSUE THREAD

**Issue by ruchitsimform** [SimformSolutionsPvtLtd/SSAppUpdater#30]
**Describe the bug**
After publishing the app on the App Store, the latest version of the app is not reflected when using the iTunes HTTP URL. However, the HTTPS URL provides the correct latest version.

**Expected behaviour**
The lookup function would give the latest published app version.

**Reference**
[https://stackoverflow.com/questions/43226752/itunes-lookup-api-return-old-data-in-my-app](https://stackoverflow.com/questions/43226752/itunes-lookup-api-return-old-data-in-my-app)

**Comment by bhargavbajani-simformsolutions** [comment]
Fixed In the latest release.
[ 1.5.0](https://github.com/SimformSolutionsPvtLtd/SSAppUpdater/releases/tag/1.5.0)
